// ── Curated exercise → YouTube video ID map ──────────────────
// Shared across workout/page.tsx, workout/today/page.tsx, plan/page.tsx, chat, etc.
export const YOUTUBE_IDS: Record<string, string> = {
  // Chest
  'bench press': 'rT7DgCr-3pg',
  'chest press': 'rT7DgCr-3pg',
  'incline bench press': 'DbFgADa2PL8',
  'incline press': 'DbFgADa2PL8',
  'decline bench press': 'EUzyhT_fwVs',
  'decline press': 'EUzyhT_fwVs',
  'push up': '_l3ySVKYVJ8',
  'push-up': '_l3ySVKYVJ8',
  'pushup': '_l3ySVKYVJ8',
  'chest fly': 'eozdVDA78K0',
  'dumbbell fly': 'eozdVDA78K0',
  'cable fly': 'Iwe6AmxVf7o',
  'pec deck': 'Iwe6AmxVf7o',
  'chest dip': '2z8JmcrW-As',
  // Back
  'pull up': 'eGo4IYlbE5g',
  'pull-up': 'eGo4IYlbE5g',
  'pullup': 'eGo4IYlbE5g',
  'chin up': 'eGo4IYlbE5g',
  'chin-up': 'eGo4IYlbE5g',
  'deadlift': 'op9kVnSso6Q',
  'romanian deadlift': 'JCXUYuzwNrM',
  'rdl': 'JCXUYuzwNrM',
  'stiff leg deadlift': 'JCXUYuzwNrM',
  'barbell row': 'kBWAon7ItDw',
  'bent over row': 'kBWAon7ItDw',
  'bent-over row': 'kBWAon7ItDw',
  'dumbbell row': 'pYcpY20QaE8',
  'one arm row': 'pYcpY20QaE8',
  'lat pulldown': 'CAwf7n6Luuc',
  'cable row': 'GZbfZ033f74',
  'seated row': 'GZbfZ033f74',
  't-bar row': 'SbZycT7Eq58',
  'face pull': 'rep-qVOkqgk',
  'hyperextension': 'mF7FBqUZojs',
  'back extension': 'mF7FBqUZojs',
  // Shoulders
  'overhead press': 'wol7Hko8RhY',
  'shoulder press': 'qEwKCR5JCog',
  'military press': 'wol7Hko8RhY',
  'ohp': 'wol7Hko8RhY',
  'lateral raise': '3VcKaXpzqRo',
  'side lateral': '3VcKaXpzqRo',
  'side raise': '3VcKaXpzqRo',
  'front raise': 'Wlc9UYPSkEY',
  'arnold press': '6Z15_WdXmVw',
  'upright row': 'jaAV-rD45I0',
  'shrug': 'cJRVVxmytaM',
  'rear delt fly': 'EA7u4Q_8HQ0',
  'rear delt raise': 'EA7u4Q_8HQ0',
  'cable lateral': '3VcKaXpzqRo',
  // Biceps
  'dumbbell curl': 'ykJmrZ5v0Oo',
  'barbell curl': 'kwG2ipFRgfo',
  'bicep curl': 'kwG2ipFRgfo',
  'biceps curl': 'kwG2ipFRgfo',
  'hammer curl': 'zC3nLlEvin4',
  'preacher curl': 'fIWP-FRFNU0',
  'concentration curl': 'Jvj2wV0vOYU',
  'incline curl': 'soxrZlIl35U',
  'cable curl': 'NFzTWp2qpiE',
  'ez bar curl': 'kwG2ipFRgfo',
  // Triceps
  'tricep dip': '0326dy_-CzM',
  'dip': '0326dy_-CzM',
  'tricep pushdown': 'vB5OHsJ3EME',
  'triceps pushdown': 'vB5OHsJ3EME',
  'cable pushdown': 'vB5OHsJ3EME',
  'pushdown': 'vB5OHsJ3EME',
  'skull crusher': 'd_KZxkY_0cM',
  'lying tricep extension': 'd_KZxkY_0cM',
  'overhead tricep extension': 'YbX7Wd8jQ-Q',
  'tricep extension': 'YbX7Wd8jQ-Q',
  'close grip bench': 'UYJsFzqdgK4',
  'diamond push': 'J0DnG1_S92I',
  'tricep kickback': '6SS6K3lAwZ8',
  'rope pushdown': 'vB5OHsJ3EME',
  // Legs
  'squat': 'ultWZbUMPL8',
  'back squat': 'ultWZbUMPL8',
  'front squat': 'uYumuL_G_V0',
  'goblet squat': 'MxsFDhcyFyE',
  'sumo squat': 'MxsFDhcyFyE',
  'leg press': 'IZxyjW7MPJQ',
  'lunge': 'QOVaHwm-Q6U',
  'walking lunge': 'L8fvypPrzzs',
  'reverse lunge': 'xrPteyQLGAo',
  'bulgarian split squat': 'hiLF_pF3EJM',
  'split squat': 'hiLF_pF3EJM',
  'leg extension': '2lvdnQg04PM',
  'leg curl': 'Orxowest56U',
  'hamstring curl': 'Orxowest56U',
  'lying leg curl': 'Orxowest56U',
  'calf raise': '3ZRe_QpvRPg',
  'standing calf raise': '3ZRe_QpvRPg',
  'seated calf raise': '3ZRe_QpvRPg',
  'hip thrust': 'qFxTNOiQIAU',
  'glute bridge': 'wPM8icPu6H8',
  'sumo deadlift': 'LGIS9vs65Sk',
  'hack squat': 'hglQExHCM9Q',
  'good morning': 'y79_KCibOm8',
  'sissy squat': 'VUiFlZ2FsKA',
  'step up': 'l4AA5d5mInQ',
  'box squat': 'ultWZbUMPL8',
  // Core
  'plank': 'ASdvN_XEl_c',
  'crunch': 'Xyd_fa5zoEU',
  'sit up': 'hYEnbuNy-h0',
  'situp': 'hYEnbuNy-h0',
  'ab rollout': 'VmqDIL2xzbk',
  'ab wheel': 'VmqDIL2xzbk',
  'russian twist': 'wkD8rjkodUI',
  'hanging leg raise': 'Pr1ieGZ5atk',
  'leg raise': 'Pr1ieGZ5atk',
  'cable crunch': 'taI4XduLpTk',
  'mountain climber': 'nmwgirgXLYM',
  'bicycle crunch': '9FGilxCbdz8',
  'dead bug': 'bxn9FBrt4-A',
  'wood chop': 'Gwcf4TOj1hc',
  'pallof press': 'axgv7H_VQOo',
  // Cardio / Compound
  'burpee': 'dZgVxmf6jkA',
  'jumping jack': 'c4DAnQ6DtF8',
  'box jump': 'G-bxQY57mKc',
  'kettlebell swing': 'YSxHifyI6s8',
  'battle rope': 'u5k-9NLlBZc',
  'jump rope': 'FJmRQ5iTXKE',
  'high knee': 'QIwxSeKpHtI',
  'jump squat': 'A-cFYWvaHr0',
}

// ── Fuzzy-match exercise name → YouTube ID ────────────────────
export function getYouTubeId(name: string): string | null {
  const lower = name.toLowerCase()
  // Exact match first
  if (YOUTUBE_IDS[lower]) return YOUTUBE_IDS[lower]
  // Substring match
  for (const [key, id] of Object.entries(YOUTUBE_IDS)) {
    if (lower.includes(key) || key.includes(lower)) return id
  }
  return null
}

// ── YouTube search URL fallback ───────────────────────────────
export function getSearchUrl(name: string): string {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(name + ' exercise tutorial proper form')}`
}
