import Link from 'next/link'
import SynapLogo from '@/components/ui/SynapLogo'

export const metadata = {
  title: 'Terms of Service — SYNAP',
  description: 'Terms and conditions for using the SYNAP AI personal training platform.',
}

const LAST_UPDATED = 'May 7, 2026'

export default function TermsPage() {
  return (
    <div className="min-h-screen" style={{ background: '#060606' }}>

      {/* Nav */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pt-6 flex items-center justify-between">
        <Link href="/"><SynapLogo size="sm" showTagline={false} /></Link>
        <Link href="/" className="font-heading text-xs tracking-widest transition-colors" style={{ color: '#475569' }}>
          ← Back
        </Link>
      </div>

      {/* Hero */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pt-14 pb-10 border-b" style={{ borderColor: 'rgba(255,255,255,0.05)' }}>
        <p className="font-heading text-xs tracking-widest uppercase mb-3" style={{ color: '#BB5CF6', letterSpacing: '0.2em' }}>LEGAL</p>
        <h1 className="font-heading font-black text-4xl text-white mb-3">Terms of Service</h1>
        <p className="font-heading text-sm" style={{ color: '#475569' }}>Last updated: {LAST_UPDATED}</p>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="flex flex-col gap-10">

          <Section title="1. Agreement to Terms">
            <P>By accessing or using SYNAP (&quot;the Service&quot;) at <strong className="text-white">synapfit.app</strong>, you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree, you may not use the Service.</P>
            <P>These Terms constitute a legally binding agreement between you and SYNAP. We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance.</P>
          </Section>

          <Section title="2. Description of Service">
            <P>SYNAP provides an AI-powered personal training platform including:</P>
            <ul className="list-disc pl-6 space-y-1.5 text-sm" style={{ color: '#94A3B8' }}>
              <li>Personalized diet and meal plans generated by Ion, our AI trainer.</li>
              <li>Custom workout programs with progressive overload and exercise guidance.</li>
              <li>Body measurement tracking, progress analytics, and composition reports.</li>
              <li>Nutrition logging via text, manual entry, and food photo scanning.</li>
              <li>AI-driven check-ins, plateau detection, and plan renewal.</li>
              <li>Supplement recommendations (Elite tier).</li>
              <li>Weekly body composition reports delivered via email (Elite tier).</li>
            </ul>
            <P>The Service is provided for general wellness purposes only. SYNAP is not a medical service, and Ion is not a licensed physician, dietitian, or certified personal trainer. Always consult a qualified healthcare professional before beginning any fitness or nutrition programme, particularly if you have pre-existing health conditions.</P>
          </Section>

          <Section title="3. Eligibility">
            <P>You must be at least 16 years of age to use SYNAP. By using the Service, you represent that you meet this requirement. If you are between 16 and 18, you must have parental or guardian consent.</P>
            <P>You must provide accurate and complete information when creating your account. You are responsible for all activity that occurs under your account.</P>
          </Section>

          <Section title="4. Accounts and Security">
            <P>You are responsible for maintaining the confidentiality of your login credentials. Do not share your password. SYNAP will never ask for your password via email or chat.</P>
            <P>You must notify us immediately at <A href="mailto:ion@synapfit.app">ion@synapfit.app</A> if you suspect any unauthorized access to your account.</P>
            <P>We reserve the right to terminate accounts that violate these Terms or are used for fraudulent, abusive, or harmful activity.</P>
          </Section>

          <Section title="5. Subscription Plans and Billing">
            <SubTitle>5.1 Plans</SubTitle>
            <P>SYNAP offers the following subscription tiers:</P>
            <ul className="list-disc pl-6 space-y-1.5 text-sm" style={{ color: '#94A3B8' }}>
              <li><strong className="text-white">Starter:</strong> Free forever. Limited to 5 Ion messages per day.</li>
              <li><strong className="text-white">Pro:</strong> Paid monthly or annually. Unlocks unlimited messages, barcode scanner, proactive check-ins, and progress photo storage.</li>
              <li><strong className="text-white">Elite:</strong> Paid monthly or annually. Includes all Pro features plus goal timeline prediction, weekly reports, and supplement recommendations.</li>
            </ul>

            <SubTitle>5.2 Free Trial</SubTitle>
            <P>Pro and Elite plans include a 7-day free trial. Your card will not be charged until day 7. If you cancel before day 7, you will not be charged — not a single riyal. Ion will remind you on days 5 and 6 of your trial.</P>

            <SubTitle>5.3 Billing</SubTitle>
            <P>All payments are processed securely by our payment provider. SYNAP does not store your payment card details. Prices are displayed in SAR and may be converted based on your location. Annual plans are billed upfront for the full year.</P>

            <SubTitle>5.4 Cancellations and Refunds</SubTitle>
            <P>You may cancel your subscription at any time from Settings → Billing. Cancellation takes effect at the end of your current billing period — you retain access until then.</P>
            <P>We do not provide refunds for partial billing periods. If you cancel during your free trial, you will not be charged.</P>

            <SubTitle>5.5 Price Changes</SubTitle>
            <P>We may change subscription prices with at least 30 days' notice. Existing subscribers will be notified by email and may cancel before the new price takes effect.</P>
          </Section>

          <Section title="6. Acceptable Use">
            <P>You agree not to:</P>
            <ul className="list-disc pl-6 space-y-1.5 text-sm" style={{ color: '#94A3B8' }}>
              <li>Use the Service for any unlawful purpose or in violation of any applicable laws.</li>
              <li>Attempt to reverse-engineer, scrape, or extract data from the Service.</li>
              <li>Use automated tools (bots, scripts) to access or interact with Ion.</li>
              <li>Impersonate another person or entity.</li>
              <li>Upload or transmit harmful, offensive, or illegal content.</li>
              <li>Attempt to gain unauthorized access to other users&apos; accounts or data.</li>
              <li>Circumvent any access controls, rate limits, or usage restrictions.</li>
              <li>Share your account credentials with others.</li>
            </ul>
            <P>Violation of these rules may result in immediate termination of your account without refund.</P>
          </Section>

          <Section title="7. Health and Safety Disclaimer">
            <P><strong className="text-white">IMPORTANT:</strong> Ion is an AI system, not a licensed medical or fitness professional. Information provided by Ion — including diet plans, workout programs, and supplement recommendations — is for general wellness guidance only and does not constitute medical advice.</P>
            <P>Before starting any diet or exercise programme, especially if you have:</P>
            <ul className="list-disc pl-6 space-y-1.5 text-sm" style={{ color: '#94A3B8' }}>
              <li>Heart, cardiovascular, or respiratory conditions</li>
              <li>Diabetes or metabolic disorders</li>
              <li>Musculoskeletal injuries or chronic pain</li>
              <li>Eating disorders or history of disordered eating</li>
              <li>Any other significant health conditions</li>
            </ul>
            <P>...you should consult a qualified physician, registered dietitian, or certified personal trainer. SYNAP and its operators are not liable for any injury, illness, or adverse outcome arising from your use of the Service.</P>
          </Section>

          <Section title="8. Intellectual Property">
            <P>All content, features, and functionality of SYNAP — including the Ion AI system, UI design, text, graphics, and code — are owned by SYNAP and protected by intellectual property laws.</P>
            <P>You retain ownership of the personal data you submit (measurements, photos, meal logs). You grant SYNAP a limited, non-exclusive licence to use this data to provide and improve the Service.</P>
            <P>You may not reproduce, distribute, or create derivative works from SYNAP content without our express written permission.</P>
          </Section>

          <Section title="9. Limitation of Liability">
            <P>To the maximum extent permitted by applicable law, SYNAP and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages — including loss of data, personal injury, or lost profits — arising from your use of the Service.</P>
            <P>Our total liability to you for any claim arising from your use of SYNAP shall not exceed the amount you paid us in the 12 months preceding the claim.</P>
          </Section>

          <Section title="10. Indemnification">
            <P>You agree to indemnify and hold harmless SYNAP and its affiliates, officers, and employees from any claims, damages, or expenses (including legal fees) arising from your violation of these Terms or your misuse of the Service.</P>
          </Section>

          <Section title="11. Termination">
            <P>You may delete your account at any time from Settings → Account. We may suspend or terminate your access immediately if you violate these Terms.</P>
            <P>Upon termination, your right to use the Service ceases. Sections 7, 8, 9, and 10 survive termination.</P>
          </Section>

          <Section title="12. Governing Law">
            <P>These Terms are governed by the laws of the Kingdom of Saudi Arabia. Any disputes shall be resolved through good-faith negotiation, and if that fails, through the competent courts in Saudi Arabia.</P>
          </Section>

          <Section title="13. Contact">
            <P>For questions about these Terms:</P>
            <P><strong className="text-white">Email:</strong> <A href="mailto:ion@synapfit.app">ion@synapfit.app</A></P>
            <P><strong className="text-white">Contact form:</strong> <A href="/contact">synapfit.app/contact</A></P>
          </Section>

        </div>
      </div>

      {/* Footer */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 flex items-center justify-between border-t" style={{ borderColor: 'rgba(255,255,255,0.05)' }}>
        <p className="font-heading text-xs" style={{ color: '#334155' }}>© 2026 SYNAP. All rights reserved.</p>
        <div className="flex items-center gap-4">
          <Link href="/privacy" className="font-heading text-xs" style={{ color: '#334155' }}>Privacy</Link>
          <Link href="/contact" className="font-heading text-xs" style={{ color: '#334155' }}>Contact</Link>
        </div>
      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="font-heading font-black text-lg text-white mb-4" style={{ letterSpacing: '0.02em' }}>{title}</h2>
      <div className="flex flex-col gap-3">{children}</div>
    </div>
  )
}

function SubTitle({ children }: { children: React.ReactNode }) {
  return (
    <p className="font-heading font-bold text-sm text-white mt-4 mb-1.5">{children}</p>
  )
}

function P({ children }: { children: React.ReactNode }) {
  return (
    <p className="font-heading text-sm leading-relaxed" style={{ color: '#94A3B8' }}>{children}</p>
  )
}

function A({ href, children }: { href: string; children: React.ReactNode }) {
  return (
    <a href={href} className="font-heading font-semibold" style={{ color: '#BB5CF6' }}>{children}</a>
  )
}
